### PR TITLE
Candidate patch to issue #15

### PR DESCRIPTION
**Pull request by mpoquet**

### CODE REVIEW

**Comment by mquinson** [comment]
@schnorr could you please have a look at that pull request? It is ways above my current understanding of the tracing subsystem..

Thanks, Mt

**Comment by mquinson** [comment]
@alegrand  is a jerk

**Comment by mquinson** [comment]
@schnorr could you please review that change, please?

**Comment by schnorr** [comment]
This commit solves a problem I was expecting to appear at some time in the future, regarding the decision of immediate execution of a Simix process. We were tracing its creation only after the Simix call, but that is dangerous since Simix might decide to run that process to the end immediately. So when the respective process container is going to be destroyed, it notices that it was never created. It looks like someone stumbled upon this problem and the proposed fix definitely solves the issue (I was able to reproduce the problem and the fix).

The solution was to create the process trace container before the Simix call. There might be still a problem here if eventually Simix decides to not create the process. If that eventually happens, we'll have a process creation that shouldn't be and the respective destroy will never come. I am not sure how often Simix decides to not create a process, but I believe the trace will survive on this scenario.

My final comment on this is that the Trace requires the pid of the process to create it. The solution proposed by @mpoquet is to use the function SIMIX_process_get_maxpid() to get the PID that will be used by  simcall_process_create to create the process. If that behavior changes in the future, it will definitely break the tracing of process creation when tracing/msg/process is enabled. But then we'll fix.

For such reasons, I recommend merging this commit. If you do, you'll have to include put this line to avoid a warning being treated as error in Trace CI:
#include "simix/smx_private.h"

@mquinson Review accomplished (on a 14th of July).

**Comment by mquinson** [comment]
Merged. On 14 of July ;)

Thanks for your time,
Mt

**Comment by mquinson** [comment]
As noted in #15, I had to revert this patch as it broke some tests. Please rework your patch and resubmit it!
I would have loved to fix the test myself, but I'm so short on time that I cannot. Sorry

**Pull request merged**
