### PR TITLE
Add a simple test for MSG_parallel_task_create

### PR DESCRIPTION
**Pull request by glesserd**
This test starts 2 parallel tasks: one with some communications, the other without.

### CODE REVIEW

**Comment by glesserd** [comment]
BTW, for those wondering how to add a new test (the documentation only speaks about unit tests):

- Copy a test that looks like yours
teshsuite/msg/$ cp -r get_sender parallel_task_create

- in this new directory, rename files according to the test name. Also, modify the CMakeLists.cmake file.

- Add a line in tools/cmake/MakeExe.cmake
> add_subdirectory(${CMAKE_HOME_DIRECTORY}/teshsuite/msg/parallel_task_create)

- Add a line in tools/cmake/Tests.cmake. You can add multiple lines here if you have multiple tests on the same directory
>  ADD_TESH_FACTORIES(tesh-msg-parallel-task         "thread;ucontext;raw" --setenv srcdir=${CMAKE_HOME_DIRECTORY}/teshsuite/msg/parallel_task_create --cd ${CMAKE_BINARY_DIR}/teshsuite/msg/parallel_task_create ${CMAKE_HOME_DIRECTORY}/teshsuite/msg/parallel_task_create/parallel_task_create.tesh)

- Add a line in tools/cmake/DefinePackages.cmake
>  teshsuite/msg/parallel_task_create/CMakeLists.txt

- Update your cmake build
build/$ make distcheck

- Now you can start your test (and only this test):
ctest -R tesh-msg-parallel-task-create

- Or if you want to start directly the binary yourself:
build/$ make parallel_task_create
teshsuite/msg/parallel_task_create/$ ../../../build/teshsuite/msg/parallel_task_create/parallel_task_create ./../../../examples/platforms/small_platform.xml parallel_task_create.xml

**Comment by mquinson** [comment]
I guess that you were looking for http://simgrid.gforge.inria.fr/simgrid/3.13/doc/inside_cmake.html#inside_cmake_addtest weren't you?

**Comment by glesserd** [comment]
The documentation explains how to add a test, not how to make it work if you are not familiar with simgrid, cmake and tesh.

I wrote this for myself, and I though that someone may benefit from it!

**Comment by mquinson** [comment]
your additional documentation is definitely a good move, thanks for that. And thanks for the example too, I'll integrate it all.

**Comment by mquinson** [comment]
Would the new documentation of the testing infrastructure (http://simgrid.gforge.inria.fr/simgrid/3.13/doc/inside_tests.html) be sufficient for you?
Pull requests are welcome on that content, too. The files are in doc/doxygen/inside_tests.doc
I will now integrate your test.

Thanks for your feedback

**Comment by glesserd** [comment]
It looks very good from my point of view! Thanks for improving the doc and reviewing my patches so quickly.

**Pull request closed without merging**
